language: ruby
rvm:
  - 2.7.0
  - 2.6.0
  - 2.5.0
gemfile:
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - bundle config set without 'appraisal'
script: bundle exec rake ci
